# Site settings
title: These Things I Can't Unlearn
email: j.e.n.s.e.r.i@gmail.com
description: “A combined project log, recipe collection, and blog by Jens Eriksson”

twitter_username: erixoneriksson
github_username:  oftatkofta
youtube_username:  oftacoftaclassic

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
